# config/aws.yml
defaults: &defaults
  access_key_id: "AKIAJ6JZVOYSE3AGOAUQ"
  secret_access_key: "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"
development:
  <<: *defaults
  bucket: "recollektionmedia-development"
test:
  <<: *defaults
  bucket: "recollektionmedia-test"
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "recollektionmedia"
